### ISSUE TITLE
Add support for war files

### ISSUE THREAD

**Issue by anders4work** [redskap/swagger-brake-maven-plugin#21]
Hi, 

thanks for a great plugin!

In my case I have the need to use it for a war file. It currently isn't working and I suspect it is because the swagger-brake project is hardcodet to search for a jar file. 

See line 42 of https://github.com/redskap/swagger-brake/blob/176a43475b85b7ceff28c253168fb5a600baa685/swagger-brake/src/main/java/io/redskap/swagger/brake/maven/maven2/Maven2UrlFactory.java

I would like to suggest that the packaging type is made optional and that the change is propagated to this project as a configurable option. 

Best,
Anders

**Comment by galovics** [comment]
Hi @anders4work,

Sure thing, we can fix anything. :))

Before jumping into coding, do you might sharing your workflow? I just wanna make sure the right thing gets implemented.

**Comment by anders4work** [comment]
Yes, of course.

I am creating a meta-plugin that tries to simplify everything swagger related. 
Adding the plugin to a server application will:

1. generate a swagger.json file compile time
2. generate a jax-rs annotated class for exposing the swagger.json
3. test for breaking changes (by calling your plugin programmatically from my meta-plugin)
4. generate various swagger-ui files and endpoints
5. generate and deploy (to binary repo) a (java)-client for the server.

It is a meta plugin so a lot of the heavy lifting of each step is done by programmatically calling a plugin capable of handling the given step. I am currently working on step 3 - and my reference project (for which I would like to use my meta-plugin) happens to be packaged as a war file. So it is a WAR file with a swagger.json file in it.

Best, Anders  
PS: Strictly speaking it is not necessary to add any configurable option in the plugin for this, since the swagger-brake-maven-plugin could just inspect the pom file to find out if the packaging is war or jar and then feed that information to a refactored version of the swagger-brake project. I haven't tested it, but I would guess that the following command would give you the information needed: 
`String packaging = project.getPackaging();`  
(where project is an instance of org.apache.maven.project.MavenProject)

**Comment by anders4work** [comment]
Do you need more info from me? 
Best, Anders

**Comment by galovics** [comment]
Hi @anders4work,

Thanks, that'll be enough to start playing with it.

I'll try to do my best and implement it during the week.

Best,
Arnold

**Comment by galovics** [comment]
Hi @anders4work.
I've just released version 2.3.0. Give it a try, looks good to me.

Let me know if you have any issues with it.

**Comment by anders4work** [comment]
Works great, thanks a lot!

**Comment by galovics** [comment]
@anders4work awesome. Thanks for the feedback.
