### ISSUE TITLE
Fail on breaking changes

### ISSUE THREAD

**Issue by ChristianLutz** [redskap/swagger-brake-maven-plugin#7]
Hello,

It would be nice if I could configure to fail the maven build if there are any breaking changes.
Either to fail after everything has been checked or fail if the first breaking change has been found doesn't matter for me.

kind regards

**Comment by galovics** [comment]
Hey @ChristianLutz, could you please elaborate on the use-case?

**Comment by ChristianLutz** [comment]
Hello @galovics 

Assume I do have a stable 1.x API and I just would like to ensure that this API stays backwards compatible. I don't want to open a report und check if it is ok or not. The build must just fail if it is not. So no accidential change slips through. 

E.g. If you have build pipeline where the last step is the deployment you don't want the software to get deployed if it contains a breaking change.

**Comment by arnold-galovics-epam** [comment]
Hey @ChristianLutz 

Totally fair point, honestly I thought I implemented it that way, I'll check it in a few days :-)

**Comment by galovics** [comment]
Implemented.

**Comment by ChristianLutz** [comment]
Thank you, I will try it
